CREATE TABLE "feedback" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"full_name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" varchar(20),
	"day_attended" varchar(50) NOT NULL,
	"overall_rating" integer NOT NULL,
	"content_quality" integer NOT NULL,
	"speaker_quality" integer NOT NULL,
	"organization_rating" integer NOT NULL,
	"venue_rating" integer NOT NULL,
	"networking_rating" integer NOT NULL,
	"most_valuable" varchar(100) NOT NULL,
	"improvements" varchar(100) NOT NULL,
	"future_topics" varchar(100) NOT NULL,
	"recommend_likelihood" varchar(50),
	"additional_comments" text,
	"workshop_feedback" text,
	"favorite_workshop" varchar(100),
	"favorite_workshop_other" varchar(255),
	"speaker_suggestions" varchar(255),
	"speaker_specialization" varchar(100),
	"share_contact" varchar(10),
	"speaker_contact" varchar(255),
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"reviewed_at" timestamp,
	"reviewed_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
