CREATE TABLE "exhibitors" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"full_name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" varchar(20) NOT NULL,
	"company_name" varchar(255),
	"years_of_operation" varchar(50),
	"website" varchar(500),
	"idea_title" varchar(255) NOT NULL,
	"category" varchar(100) NOT NULL,
	"field_of_focus" varchar(255) NOT NULL,
	"areas_of_interest" varchar(500),
	"uniqueness" text NOT NULL,
	"summary" text NOT NULL,
	"business_model" text NOT NULL,
	"target_market" text NOT NULL,
	"want_to_team_up" varchar(10) NOT NULL,
	"looking_for" text,
	"sdg_alignment" text NOT NULL,
	"other_sdg" varchar(500),
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"reviewed_at" timestamp,
	"reviewed_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
